Feature/responsive layout
ishiro-io/ishiro-mobile pull request #20
Opened 2021-02-15 16:19 UTC by MaelissCoue

2021-02-15 16:29 UTC, Nolat requested changes

2021-02-15 16:29 UTC, Nolat commented on src/components/AnimeCard.tsx
> +            height: height * 0.8,
Pourquoi ne pas utiliser RFPercentage ici ?

2021-02-15 16:29 UTC, Nolat commented on src/components/AnimeCard.tsx
> +            height: height * 0.8,
Same

2021-02-15 16:29 UTC, Nolat commented on src/components/AnimeCard.tsx
> +            height: height * 0.8
Same

2021-02-15 16:29 UTC, Nolat commented on src/components/AnimeCard.tsx
> +              height: height * 0.8
Same

2021-02-15 16:29 UTC, Nolat commented on src/routes/Authentication/AskConfirmPhoneNumberCode/AskConfirmPhoneNumberCode.tsx
> +                  width: width * 0.9
Same

2021-02-15 16:29 UTC, Nolat commented on src/routes/Authentication/ConfirmPhoneNumberCode/ConfirmPhoneNumberCode.tsx
> +              width: width * 0.9
Same

2021-02-15 16:29 UTC, Nolat commented on src/routes/Authentication/ConfirmPhoneNumberCode/ConfirmPhoneNumberCode.tsx
> +          <View style={{ height: 50 }}>
Ici, on devrait plus avoir de taille fixe non ?

2021-02-15 16:29 UTC, Nolat commented on src/routes/Authentication/ConfirmPhoneNumberCode/SetUsername/SetUsername.tsx
> +                  width: width * 0.9
Same

2021-02-15 16:29 UTC, Nolat commented on src/routes/Authentication/Onboarding/AppleAuthButton/AppleAuthButton.tsx
> +        width: width * 0.9,
Same

2021-02-15 16:29 UTC, Nolat commented on src/routes/Authentication/Onboarding/FacebookAuthButton/FacebookAuthButton.tsx
> +        width: width * 0.9,
Same

2021-02-15 16:29 UTC, Nolat commented on src/routes/Authentication/Onboarding/GoogleAuthButton/GoogleAuthButton.tsx
> +        width: width * 0.9,
Same

2021-02-15 16:29 UTC, Nolat commented on src/routes/Authentication/Onboarding/Onboarding.tsx
> +          width: width * 0.9,
Same

2021-02-15 16:29 UTC, Nolat commented on src/routes/Content/Main/Home/FlatPreviewList/HomePreviewList/SeeMoreCard/SeeMoreCard.tsx
> +            fontSize: 14,
fontSize en dur

2021-02-15 16:35 UTC, MaelissCoue commented on src/components/AnimeCard.tsx
> +            height: height * 0.8,
A voir ensemble pour régler la taille des cartes

2021-02-15 16:35 UTC, MaelissCoue commented on src/components/AnimeCard.tsx
> +            height: height * 0.8,
A voir ensemble pour régler la taille des cartes

2021-02-15 16:35 UTC, MaelissCoue commented on src/components/AnimeCard.tsx
> +            height: height * 0.8
A voir ensemble pour régler la taille des cartes

2021-02-15 16:36 UTC, MaelissCoue commented on src/components/AnimeCard.tsx
> +              height: height * 0.8
A voir ensemble pour régler la taille des cartes

2021-02-15 16:38 UTC, MaelissCoue commented on src/routes/Authentication/ConfirmPhoneNumberCode/ConfirmPhoneNumberCode.tsx
> +          <View style={{ height: 50 }}>
C'est juste la taille du conteneur pour l'erreur, mais je pense qu'on peut la retirer carrément

2021-02-15 16:39 UTC, MaelissCoue commented on src/routes/Content/Main/Home/FlatPreviewList/HomePreviewList/SeeMoreCard/SeeMoreCard.tsx
> +            fontSize: 14,
yes, car en responsive ça rends pas bien, j'ai préféré laisser une taille en dur, l'amplitude est trop grande avec le RFPercentage

2021-02-15 16:40 UTC, MaelissCoue commented on src/routes/Authentication/Onboarding/Onboarding.tsx
> +          width: width * 0.9,
J'vais retester demain si le RFPercentage rends bien

2021-02-15 16:40 UTC, MaelissCoue commented on src/routes/Authentication/Onboarding/GoogleAuthButton/GoogleAuthButton.tsx
> +        width: width * 0.9,
J'vais retester demain si le RFPercentage rends bien

2021-02-15 16:40 UTC, MaelissCoue commented on src/routes/Authentication/Onboarding/FacebookAuthButton/FacebookAuthButton.tsx
> +        width: width * 0.9,
J'vais retester demain si le RFPercentage rends bien

2021-02-15 16:40 UTC, MaelissCoue commented on src/routes/Authentication/Onboarding/AppleAuthButton/AppleAuthButton.tsx
> +        width: width * 0.9,
J'vais retester demain si le RFPercentage rends bien

2021-02-15 16:40 UTC, MaelissCoue commented on src/routes/Authentication/ConfirmPhoneNumberCode/SetUsername/SetUsername.tsx
> +                  width: width * 0.9
J'vais retester demain si le RFPercentage rends bien

2021-02-15 16:40 UTC, MaelissCoue commented on src/routes/Authentication/ConfirmPhoneNumberCode/ConfirmPhoneNumberCode.tsx
> +              width: width * 0.9
J'vais retester demain si le RFPercentage rends bien

2021-02-15 16:40 UTC, MaelissCoue commented on src/routes/Authentication/AskConfirmPhoneNumberCode/AskConfirmPhoneNumberCode.tsx
> +                  width: width * 0.9
J'vais retester demain si le RFPercentage rends bien

2021-02-16 07:25 UTC, Nolat approved these changes

2021-02-17 08:42 UTC, closed without merging